redis:
  host: ${redis.hosts:localhost}
  port: ${redis.ports:6390}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:template;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE # change this to your database type, postgresql, mysql or other
  test:
    database:
      replace: none
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
    locations: classpath:db/migration