logging:
  level:
    ROOT: WARN
    com.kaua.template: DEBUG

server:
  port: 8081
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  flyway:
    enabled: false
  datasource: # change this to your database, postgresql, mysql or other
    url: jdbc:postgresql://${postgres.url}/${postgres.schema}
    username: ${postgres.username}
    password: ${postgres.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect # change this to your database, postgresql, mysql or other
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true

# expondo rotas: /actuator/<health, info, metrics>
management:
  endpoints.web.exposure.include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    export:
      otlp:
        step: 15s
    enable-all: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      slo[http.server.requests]: "25ms, 50ms, 100ms, 200ms, 400ms, 800ms, 1500ms"

otel: # https://medium.com/@yangli136/how-opentelemetry-is-integrated-with-spring-boot-application-7e309efc0011
  metrics:
    enabled: true
    export:
      interval: 10s
  propagation:
    enabled: true
  propagators:
    - b3
  traces:
    export:
      interval: 10s
  logs:
    enabled: true
    export:
      interval: 10s
#    exporter: none change to otlp
  resource:
    attributes:
      service:
        name: template