receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  elasticsearch:
    endpoint: http://elasticsearch:9200
    tls:
      insecure_skip_verify: true
    logs_index: "observability-logs"
#    mapping: # default is none
#      mode: ecs
#    user: "elastic"
#    password: "elastic"
  prometheus:
    endpoint: 0.0.0.0:9464

processors:
  transform:
    log_statements:
      - context: log
        statements:
          - delete_key(attributes, "code.function")
          - delete_key(attributes, "code.lineno")

  resource:
    attributes:
      - key: "process.pid"
        action: delete
      - key: "process.executable.path"
        action: delete
      - key: "process.command_line"
        action: delete
      - key: "process.runtime.name"
        action: delete
      - key: "telemetry.sdk.language"
        action: delete
      - key: "telemetry.sdk.name"
        action: delete
      - key: "telemetry.sdk.version"
        action: delete

  batch: {}

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs: # https://www.elastic.co/observability-labs/blog/logstash-to-otel
      receivers: [otlp]
      processors: [transform, resource]
      exporters: [elasticsearch]