name: CI - Run tests after push

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      - refactor/*
      - fix/*
      - docs/*
      - release/*
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Execute tests
        run: ./gradlew test --rerun-tasks --stacktrace